image: maven:3.9.16-eclipse-temurin-26-alpine

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

test:
  stage: test
  script:
    - mvn --batch-mode --no-transfer-progress test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
